### ISSUE TITLE
runing isuse

### ISSUE THREAD

**Issue by sara9096** [pmarella2/GenVote#2]
hi there
thank you for sharing this perfect project with us
i try to run your project in ganache and it works but when i try to register in order to create ballot whatever i write there it says invalid email address
i'm wondering should i change any address in your code with my ganache address to make it work?

**Comment by pmarella2** [comment]
It only accepts certain e-mail domains, the accepted one can be found in this contract: https://github.com/pmarella2/GenVote/blob/master/migrations/2_deploy_contracts.js

**Comment by pmarella2** [comment]
Closing on the assumption that you have solved this issue.
